// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusAPI;

#nullable disable

namespace NexusAPI.Migrations
{
    [DbContext(typeof(NexusDbContext))]
    [Migration("20260309130919_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NexusAPI.Models.Achievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Achievements");
                });

            modelBuilder.Entity("NexusAPI.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActivityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("Activities");

                    b.HasDiscriminator().HasValue("Activity");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("NexusAPI.Models.EventRecurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateEnd")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EventRecurrence");
                });

            modelBuilder.Entity("NexusAPI.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("NexusAPI.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateTimeEnd")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateTimeStart")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("EventRecurrenceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("EventRecurrenceId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("NexusAPI.Models.SessionAchievement", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("AchievementId")
                        .HasColumnType("int");

                    b.HasKey("SessionId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("SessionAchievements");
                });

            modelBuilder.Entity("NexusAPI.Models.SmartReminder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DateAlert")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("TimeAlert")
                        .IsRequired()
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("SmartReminders");
                });

            modelBuilder.Entity("NexusAPI.Models.Class", b =>
                {
                    b.HasBaseType("NexusAPI.Models.Activity");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Teacher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Class");
                });

            modelBuilder.Entity("NexusAPI.Models.ExtraActivity", b =>
                {
                    b.HasBaseType("NexusAPI.Models.Activity");

                    b.Property<string>("Organiser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ExtraActivity");
                });

            modelBuilder.Entity("NexusAPI.Models.Sport", b =>
                {
                    b.HasBaseType("NexusAPI.Models.Activity");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Intensity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Activities", t =>
                        {
                            t.Property("Place")
                                .HasColumnName("Sport_Place");
                        });

                    b.HasDiscriminator().HasValue("Sport");
                });

            modelBuilder.Entity("NexusAPI.Models.Activity", b =>
                {
                    b.HasOne("NexusAPI.Models.Activity", null)
                        .WithMany("Activities")
                        .HasForeignKey("ActivityId");
                });

            modelBuilder.Entity("NexusAPI.Models.Session", b =>
                {
                    b.HasOne("NexusAPI.Models.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Models.EventRecurrence", "EventRecurrence")
                        .WithMany("Sessions")
                        .HasForeignKey("EventRecurrenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");

                    b.Navigation("EventRecurrence");
                });

            modelBuilder.Entity("NexusAPI.Models.SessionAchievement", b =>
                {
                    b.HasOne("NexusAPI.Models.Achievement", "Achievement")
                        .WithMany("SessionAchievements")
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusAPI.Models.Session", "Session")
                        .WithMany("SessionAchievements")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NexusAPI.Models.SmartReminder", b =>
                {
                    b.HasOne("NexusAPI.Models.Session", "Session")
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("NexusAPI.Models.Achievement", b =>
                {
                    b.Navigation("SessionAchievements");
                });

            modelBuilder.Entity("NexusAPI.Models.Activity", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("NexusAPI.Models.EventRecurrence", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("NexusAPI.Models.Session", b =>
                {
                    b.Navigation("SessionAchievements");
                });
#pragma warning restore 612, 618
        }
    }
}
